// THIS FILE WAS AUTOGENERATED BY FILE generateTestSuite.py
#include "testSuite.h" 
#include "test.h"

void GetFirstItemUsingSubscriptOperator_GetsItem();
void GetSecondItemUsingSubscriptOperator_GetsSecondItem();
void AddItemToList_ListContainsItem();
void AddOneItemToList_ItemBecomesHead();
void AddOneItemToList_ItemBecomesTail();
void AddTwoItemsToList_FirstIsHeadSecondIsTail();
void AddMultipleItemsToList_FirstlyAddedIsHeadLastlyAddedIsTail();

void RunTests() 
{
	RUN_TEST(GetFirstItemUsingSubscriptOperator_GetsItem);
	RUN_TEST(GetSecondItemUsingSubscriptOperator_GetsSecondItem);
	RUN_TEST(AddItemToList_ListContainsItem);
	RUN_TEST(AddOneItemToList_ItemBecomesHead);
	RUN_TEST(AddOneItemToList_ItemBecomesTail);
	RUN_TEST(AddTwoItemsToList_FirstIsHeadSecondIsTail);
	RUN_TEST(AddMultipleItemsToList_FirstlyAddedIsHeadLastlyAddedIsTail);
}
